### ISSUE TITLE
Novice to python

### ISSUE THREAD

**Issue by Devinaseeruttun** [jambler24/GenGraph#12]
I am having this problem can you help please? Thank you
devina@devina-HP-ProBook-450-G3:~/GenGraph$ python3 gengraphTool.py make_genome_graph --seq_file analysis.txt --out_file_name test --recreate_check
Traceback (most recent call last):
  File "gengraphTool.py", line 83, in <module>
    parsed_input_dict = parse_seq_file(args.seq_file)
  File "/home/devina/GenGraph/gengraph.py", line 548, in parse_seq_file
    A_seq_label_dict[a_seq_file['aln_name']] = a_seq_file['seq_name']
KeyError: 'seq_name'

**Comment by jambler24** [comment]
copy and paste the analysis.txt file here? I think something in the formatting is causing trouble

**Comment by mvtullius** [comment]
I had the same issue. The problem was the text file had some hidden characters at the start of the file that weren't showing up in the text editor. I think this was because I originally copied the text from the website. When I made a new text file it worked without the error.

**Comment by jambler24** [comment]
Thanks for the comment @mvtullius, adding in some input checking to try catch problems like this.

**Comment by jambler24** [comment]
Closing this for now, if it happens again please let me know so I can improve the input checking.

Thanks!
