### ISSUE TITLE
[BUG?] Error: progressiveMauve_call error: output of progressiveMauve empty

### ISSUE THREAD

**Issue by minu7** [jambler24/GenGraph#30]
When i run this script:
python ./gengraphTool.py make_genome_graph --seq_file TestGraphs/sequences.txt --out_file_name test
sequences.txt: 
```
seq_name	aln_name	seq_path	annotation_path
H37Rv	seq0	/Users/filippo/Desktop/workspace/GenGraph/TestGraphs/H37Rv.fa	NA
H37Rv1	seq1	/Users/filippo/Desktop/workspace/GenGraph/TestGraphs/H37Rv1.fa	Na
H37Rv2	seq2	/Users/filippo/Desktop/workspace/GenGraph/TestGraphs/H37Rv2.fa	N
```
I got the error:
**progressiveMauve_call error: output of progressiveMauve empty**

I fixed the error changing the line 2775 in gengraph.py:
old line: number_of_lines = **3** ----- new line: number_of_lines = **2**

But i'm not sure about the fix

Thank you!

**Comment by jambler24** [comment]
Thanks @minu7 , I'll have a look at the fix and see what is going on there

**Comment by jambler24** [comment]
Changed value to 2, the value of 3 was too strict and assumed that there would always be at least 2 blocks.

**Comment by minu7** [comment]
@jambler24 Great, thank you!
